### ISSUE TITLE
Deploy only frontend or backend

### ISSUE THREAD

**Issue by ArunEPRO** [Azure-Samples/azure-search-openai-demo#266]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> How to deploy only backend files or frontend files. I added 150MB of enterprise data and deployed the entire environment. Now I need to update single file in frontend or backend. If I give azd up - entire environment (frontend, backend, data files, etc are getting deployed)

### Any log messages given by the failure
> no

### Expected/desired behavior
> Only selected backend or front end must be deployed based on need. 

### OS and Version?
> Linux - App Service

### azd version?
> azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

**Comment by den130** [comment]
If you just want to update indexes, you can run the script:

`.\scripts\prepdocs.ps1`

**Comment by ArunEPRO** [comment]
I understand you mean data folder as indexes. Yes ".\scripts\prepdocs.ps1" can be used for updating the data.

I need to make a change to the UI or prompt. azd up is not a very good solution as it incurs me additional cost by reuploading all data.

Is there an option for that ?

**Comment by dvag-christian-ley** [comment]
You can comment out the hook in the `azure.yaml` to stop `azd up` from reuploading on every frontend/backend change that you want to upload.

```yaml
name: azure-search-openai-demo
metadata:
  template: azure-search-openai-demo@0.0.2-beta
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run: cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run: cd ../frontend;npm install;npm run build
          interactive: true
          continueOnError: false
# hooks:
#     postprovision:
#       windows:
#         shell: pwsh
#         run: ./scripts/prepdocs.ps1
#         interactive: true
#         continueOnError: false
#       posix:
#         shell: sh
#         run: ./scripts/prepdocs.sh
#         interactive: true
#         continueOnError: false
```
